DROP DATABASE IF EXISTS TALKUP;
CREATE DATABASE TALKUP;
USE TALKUP;

CREATE TABLE IF NOT EXISTS ROLES(
ID					INT				NOT NULL	PRIMARY KEY,
DESCRIPCION			VARCHAR(25)		NOT NULL
);

CREATE TABLE IF NOT EXISTS GRUPOS(
ID					INT				NOT NULL	PRIMARY KEY,
DESCRIPCION			VARCHAR(25)		NOT NULL
);

CREATE TABLE IF NOT EXISTS USUARIOS(
ID					INT				NOT NULL 	PRIMARY KEY		AUTO_INCREMENT,
NICK				VARCHAR(50)		NOT NULL,
CLAVE				VARCHAR(32)		NOT NULL,
NOMBRE				VARCHAR(50)		NOT NULL,
APELLIDO			VARCHAR(50)		NOT NULL,
EMAIL				VARCHAR(100)	NOT NULL,
DIRECCION			VARCHAR(100)	NOT NULL,
TELEFONO			INT(8)			NOT NULL,
IDROL				INT				NOT NULL,
IDGRUPO				INT				NOT NULL,

FOREIGN KEY (IDROL) 	REFERENCES ROLES(ID) 	ON DELETE CASCADE,
FOREIGN KEY (IDGRUPO)	REFERENCES GRUPOS(ID)	ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS JUEGOS(
ID					INT				NOT NULL	PRIMARY KEY,
DESCRIPCION			VARCHAR(12)		NOT NULL
);


CREATE TABLE IF NOT EXISTS PUNTAJES(
ID					INT				NOT NULL	PRIMARY KEY		AUTO_INCREMENT,
IDUSUARIO			INT				NOT NULL,
IDJUEGO				INT				NOT NULL,
PUNTUACION			INT				NOT NULL,

FOREIGN KEY (IDUSUARIO)	REFERENCES USUARIOS(ID)	ON DELETE CASCADE,
FOREIGN KEY (IDJUEGO)	REFERENCES JUEGOS(ID) ON DELETE CASCADE
);


INSERT INTO JUEGOS
(ID, DESCRIPCION) VALUES
('1','Emociones');

INSERT INTO ROLES
(ID, DESCRIPCION) VALUES
('1', 'Administrador'),
('2', 'Instructor'),
('3', 'Alumno');

INSERT INTO GRUPOS
(ID, DESCRIPCION) VALUES
('1', 'Primero'),
('2', 'Segundo'),
('3', 'Tercero');

INSERT INTO USUARIOS
(NICK, CLAVE, NOMBRE, APELLIDO, TELEFONO, DIRECCION, EMAIL, IDROL, IDGRUPO) VALUES
('admin', '827ccb0eea8a706c4c34a16891f84e7b', 'adriana', 'membreño', '22772277', 'ejemplo', 'Ejemplo@ej.com', '1', '1');